// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/model.proto

package v1alpha1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_DIR  FileType = 0
	FileType_FILE FileType = 1
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "DIR",
		1: "FILE",
	}
	FileType_value = map[string]int32{
		"DIR":  0,
		"FILE": 1,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_model_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_v1alpha1_model_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{0}
}

type Category int32

const (
	Category_TASK     Category = 0
	Category_LIBRARY  Category = 1
	Category_LICENSE  Category = 2
	Category_LANGUAGE Category = 3
	Category_OTHER    Category = 4
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "TASK",
		1: "LIBRARY",
		2: "LICENSE",
		3: "LANGUAGE",
		4: "OTHER",
	}
	Category_value = map[string]int32{
		"TASK":     0,
		"LIBRARY":  1,
		"LICENSE":  2,
		"LANGUAGE": 3,
		"OTHER":    4,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_model_proto_enumTypes[1].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_v1alpha1_model_proto_enumTypes[1]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{1}
}

type ListModelTaskLabelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelTaskLabelsRequest) Reset() {
	*x = ListModelTaskLabelsRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelTaskLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelTaskLabelsRequest) ProtoMessage() {}

func (x *ListModelTaskLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelTaskLabelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelTaskLabelsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{0}
}

type ListModelTaskLabelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Label               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelTaskLabelsResponse) Reset() {
	*x = ListModelTaskLabelsResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelTaskLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelTaskLabelsResponse) ProtoMessage() {}

func (x *ListModelTaskLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelTaskLabelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelTaskLabelsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{1}
}

func (x *ListModelTaskLabelsResponse) GetItems() []*Label {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListModelFrameLabelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelFrameLabelsRequest) Reset() {
	*x = ListModelFrameLabelsRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelFrameLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelFrameLabelsRequest) ProtoMessage() {}

func (x *ListModelFrameLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelFrameLabelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelFrameLabelsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{2}
}

type ListModelFrameLabelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Label               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelFrameLabelsResponse) Reset() {
	*x = ListModelFrameLabelsResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelFrameLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelFrameLabelsResponse) ProtoMessage() {}

func (x *ListModelFrameLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelFrameLabelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelFrameLabelsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{3}
}

func (x *ListModelFrameLabelsResponse) GetItems() []*Label {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []string               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Project       string                 `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Popular       bool                   `protobuf:"varint,7,opt,name=popular,proto3" json:"popular,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{4}
}

func (x *ListModelsRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListModelsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListModelsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListModelsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListModelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListModelsRequest) GetPopular() bool {
	if x != nil {
		return x.Popular
	}
	return false
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Model               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{5}
}

func (x *ListModelsResponse) GetItems() []*Model {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListModelsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{6}
}

func (x *GetModelRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{7}
}

func (x *CreateModelRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelResponse) Reset() {
	*x = CreateModelResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelResponse) ProtoMessage() {}

func (x *CreateModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelResponse.ProtoReflect.Descriptor instead.
func (*CreateModelResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{8}
}

type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteModelRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DeleteModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelResponse) Reset() {
	*x = DeleteModelResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelResponse) ProtoMessage() {}

func (x *DeleteModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{10}
}

type ListModelRevisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelRevisionsRequest) Reset() {
	*x = ListModelRevisionsRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelRevisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelRevisionsRequest) ProtoMessage() {}

func (x *ListModelRevisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelRevisionsRequest.ProtoReflect.Descriptor instead.
func (*ListModelRevisionsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{11}
}

func (x *ListModelRevisionsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListModelRevisionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListModelRevisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         *Revisions             `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelRevisionsResponse) Reset() {
	*x = ListModelRevisionsResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelRevisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelRevisionsResponse) ProtoMessage() {}

func (x *ListModelRevisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelRevisionsResponse.ProtoReflect.Descriptor instead.
func (*ListModelRevisionsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{12}
}

func (x *ListModelRevisionsResponse) GetItems() *Revisions {
	if x != nil {
		return x.Items
	}
	return nil
}

type Revisions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*Revision            `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	Tags          []*Revision            `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revisions) Reset() {
	*x = Revisions{}
	mi := &file_v1alpha1_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revisions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revisions) ProtoMessage() {}

func (x *Revisions) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revisions.ProtoReflect.Descriptor instead.
func (*Revisions) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{13}
}

func (x *Revisions) GetBranches() []*Revision {
	if x != nil {
		return x.Branches
	}
	return nil
}

func (x *Revisions) GetTags() []*Revision {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListModelCommitsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Project  string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Revision string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	// If true, include diff information for each commit.
	// Default is false to avoid returning large amounts of data.
	Diff          bool  `protobuf:"varint,4,opt,name=diff,proto3" json:"diff,omitempty"`
	Page          int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelCommitsRequest) Reset() {
	*x = ListModelCommitsRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelCommitsRequest) ProtoMessage() {}

func (x *ListModelCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelCommitsRequest.ProtoReflect.Descriptor instead.
func (*ListModelCommitsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{14}
}

func (x *ListModelCommitsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListModelCommitsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListModelCommitsRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ListModelCommitsRequest) GetDiff() bool {
	if x != nil {
		return x.Diff
	}
	return false
}

func (x *ListModelCommitsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelCommitsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListModelCommitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Commit              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelCommitsResponse) Reset() {
	*x = ListModelCommitsResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelCommitsResponse) ProtoMessage() {}

func (x *ListModelCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelCommitsResponse.ProtoReflect.Descriptor instead.
func (*ListModelCommitsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{15}
}

func (x *ListModelCommitsResponse) GetItems() []*Commit {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListModelCommitsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetModelCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelCommitRequest) Reset() {
	*x = GetModelCommitRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelCommitRequest) ProtoMessage() {}

func (x *GetModelCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelCommitRequest.ProtoReflect.Descriptor instead.
func (*GetModelCommitRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{16}
}

func (x *GetModelCommitRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetModelCommitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetModelCommitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetModelTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Revision      string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelTreeRequest) Reset() {
	*x = GetModelTreeRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelTreeRequest) ProtoMessage() {}

func (x *GetModelTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelTreeRequest.ProtoReflect.Descriptor instead.
func (*GetModelTreeRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{17}
}

func (x *GetModelTreeRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetModelTreeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetModelTreeRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *GetModelTreeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type File struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type   FileType               `protobuf:"varint,2,opt,name=type,proto3,enum=matrixhub.v1alpha1.FileType" json:"type,omitempty"`
	Path   string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Size   int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Lfs    bool                   `protobuf:"varint,5,opt,name=lfs,proto3" json:"lfs,omitempty"`
	Sha256 string                 `protobuf:"bytes,6,opt,name=Sha256,proto3" json:"Sha256,omitempty"`
	// commit with out diffs
	// only file type have commit
	Commit        *Commit `protobuf:"bytes,7,opt,name=commit,proto3" json:"commit,omitempty"`
	Url           string  `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_v1alpha1_model_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{18}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_DIR
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetLfs() bool {
	if x != nil {
		return x.Lfs
	}
	return false
}

func (x *File) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *File) GetCommit() *Commit {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetModelTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*File                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelTreeResponse) Reset() {
	*x = GetModelTreeResponse{}
	mi := &file_v1alpha1_model_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelTreeResponse) ProtoMessage() {}

func (x *GetModelTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelTreeResponse.ProtoReflect.Descriptor instead.
func (*GetModelTreeResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{19}
}

func (x *GetModelTreeResponse) GetItems() []*File {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetModelBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Revision      string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelBlobRequest) Reset() {
	*x = GetModelBlobRequest{}
	mi := &file_v1alpha1_model_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelBlobRequest) ProtoMessage() {}

func (x *GetModelBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelBlobRequest.ProtoReflect.Descriptor instead.
func (*GetModelBlobRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{20}
}

func (x *GetModelBlobRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetModelBlobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetModelBlobRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *GetModelBlobRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Model struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname       string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	DefaultBranch  string                 `protobuf:"bytes,4,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CloneUrls      *CloneUrls             `protobuf:"bytes,7,opt,name=clone_urls,json=cloneUrls,proto3" json:"clone_urls,omitempty"`
	Labels         []*Label               `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	Project        string                 `protobuf:"bytes,9,opt,name=project,proto3" json:"project,omitempty"`
	ReadmeContent  string                 `protobuf:"bytes,10,opt,name=readme_content,json=readmeContent,proto3" json:"readme_content,omitempty"`
	Size           string                 `protobuf:"bytes,11,opt,name=size,proto3" json:"size,omitempty"`
	ParameterCount string                 `protobuf:"bytes,12,opt,name=parameter_count,json=parameterCount,proto3" json:"parameter_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_v1alpha1_model_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{21}
}

func (x *Model) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Model) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *Model) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Model) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Model) GetCloneUrls() *CloneUrls {
	if x != nil {
		return x.CloneUrls
	}
	return nil
}

func (x *Model) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Model) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Model) GetReadmeContent() string {
	if x != nil {
		return x.ReadmeContent
	}
	return ""
}

func (x *Model) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Model) GetParameterCount() string {
	if x != nil {
		return x.ParameterCount
	}
	return ""
}

type CloneUrls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SshUrl        string                 `protobuf:"bytes,1,opt,name=ssh_url,json=sshUrl,proto3" json:"ssh_url,omitempty"`
	HttpUrl       string                 `protobuf:"bytes,2,opt,name=http_url,json=httpUrl,proto3" json:"http_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneUrls) Reset() {
	*x = CloneUrls{}
	mi := &file_v1alpha1_model_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneUrls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneUrls) ProtoMessage() {}

func (x *CloneUrls) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneUrls.ProtoReflect.Descriptor instead.
func (*CloneUrls) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{22}
}

func (x *CloneUrls) GetSshUrl() string {
	if x != nil {
		return x.SshUrl
	}
	return ""
}

func (x *CloneUrls) GetHttpUrl() string {
	if x != nil {
		return x.HttpUrl
	}
	return ""
}

type Revision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_v1alpha1_model_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{23}
}

func (x *Revision) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Commit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AuthorName     string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail    string                 `protobuf:"bytes,4,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	AuthorDate     string                 `protobuf:"bytes,5,opt,name=author_date,json=authorDate,proto3" json:"author_date,omitempty"`
	CommitterName  string                 `protobuf:"bytes,6,opt,name=committer_name,json=committerName,proto3" json:"committer_name,omitempty"`
	CommitterEmail string                 `protobuf:"bytes,7,opt,name=committer_email,json=committerEmail,proto3" json:"committer_email,omitempty"`
	Diff           string                 `protobuf:"bytes,8,opt,name=diff,proto3" json:"diff,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_v1alpha1_model_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{24}
}

func (x *Commit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Commit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Commit) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Commit) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *Commit) GetAuthorDate() string {
	if x != nil {
		return x.AuthorDate
	}
	return ""
}

func (x *Commit) GetCommitterName() string {
	if x != nil {
		return x.CommitterName
	}
	return ""
}

func (x *Commit) GetCommitterEmail() string {
	if x != nil {
		return x.CommitterEmail
	}
	return ""
}

func (x *Commit) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *Commit) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Commit) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      Category               `protobuf:"varint,3,opt,name=category,proto3,enum=matrixhub.v1alpha1.Category" json:"category,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_v1alpha1_model_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_model_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_v1alpha1_model_proto_rawDescGZIP(), []int{25}
}

func (x *Label) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_TASK
}

func (x *Label) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Label) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_v1alpha1_model_proto protoreflect.FileDescriptor

const file_v1alpha1_model_proto_rawDesc = "" +
	"\n" +
	"\x14v1alpha1/model.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x14v1alpha1/utils.proto\"\x1c\n" +
	"\x1aListModelTaskLabelsRequest\"N\n" +
	"\x1bListModelTaskLabelsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.matrixhub.v1alpha1.LabelR\x05items\"\x1d\n" +
	"\x1bListModelFrameLabelsRequest\"O\n" +
	"\x1cListModelFrameLabelsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.matrixhub.v1alpha1.LabelR\x05items\"\xbc\x01\n" +
	"\x11ListModelsRequest\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x18\n" +
	"\aproject\x18\x04 \x01(\tR\aproject\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x18\n" +
	"\apopular\x18\a \x01(\bR\apopular\"\x85\x01\n" +
	"\x12ListModelsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.matrixhub.v1alpha1.ModelR\x05items\x12>\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1e.matrixhub.v1alpha1.PaginationR\n" +
	"pagination\"Q\n" +
	"\x0fGetModelRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"T\n" +
	"\x12CreateModelRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"\x15\n" +
	"\x13CreateModelResponse\"T\n" +
	"\x12DeleteModelRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"\x15\n" +
	"\x13DeleteModelResponse\"[\n" +
	"\x19ListModelRevisionsRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"Q\n" +
	"\x1aListModelRevisionsResponse\x123\n" +
	"\x05items\x18\x01 \x01(\v2\x1d.matrixhub.v1alpha1.RevisionsR\x05items\"w\n" +
	"\tRevisions\x128\n" +
	"\bbranches\x18\x01 \x03(\v2\x1c.matrixhub.v1alpha1.RevisionR\bbranches\x120\n" +
	"\x04tags\x18\x02 \x03(\v2\x1c.matrixhub.v1alpha1.RevisionR\x04tags\"\xba\x01\n" +
	"\x17ListModelCommitsRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12\x12\n" +
	"\x04diff\x18\x04 \x01(\bR\x04diff\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\x8c\x01\n" +
	"\x18ListModelCommitsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.matrixhub.v1alpha1.CommitR\x05items\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.matrixhub.v1alpha1.PaginationR\n" +
	"pagination\"p\n" +
	"\x15GetModelCommitRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x17\n" +
	"\x02id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"\x85\x01\n" +
	"\x13GetModelTreeRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\xe4\x01\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.matrixhub.v1alpha1.FileTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x10\n" +
	"\x03lfs\x18\x05 \x01(\bR\x03lfs\x12\x16\n" +
	"\x06Sha256\x18\x06 \x01(\tR\x06Sha256\x122\n" +
	"\x06commit\x18\a \x01(\v2\x1a.matrixhub.v1alpha1.CommitR\x06commit\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\"F\n" +
	"\x14GetModelTreeResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.matrixhub.v1alpha1.FileR\x05items\"\x85\x01\n" +
	"\x13GetModelBlobRequest\x12!\n" +
	"\aproject\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproject\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\x9b\x03\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12%\n" +
	"\x0edefault_branch\x18\x04 \x01(\tR\rdefaultBranch\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12<\n" +
	"\n" +
	"clone_urls\x18\a \x01(\v2\x1d.matrixhub.v1alpha1.CloneUrlsR\tcloneUrls\x121\n" +
	"\x06labels\x18\b \x03(\v2\x19.matrixhub.v1alpha1.LabelR\x06labels\x12\x18\n" +
	"\aproject\x18\t \x01(\tR\aproject\x12%\n" +
	"\x0ereadme_content\x18\n" +
	" \x01(\tR\rreadmeContent\x12\x12\n" +
	"\x04size\x18\v \x01(\tR\x04size\x12'\n" +
	"\x0fparameter_count\x18\f \x01(\tR\x0eparameterCount\"?\n" +
	"\tCloneUrls\x12\x17\n" +
	"\assh_url\x18\x01 \x01(\tR\x06sshUrl\x12\x19\n" +
	"\bhttp_url\x18\x02 \x01(\tR\ahttpUrl\"\x1e\n" +
	"\bRevision\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xb9\x02\n" +
	"\x06Commit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x04 \x01(\tR\vauthorEmail\x12\x1f\n" +
	"\vauthor_date\x18\x05 \x01(\tR\n" +
	"authorDate\x12%\n" +
	"\x0ecommitter_name\x18\x06 \x01(\tR\rcommitterName\x12'\n" +
	"\x0fcommitter_email\x18\a \x01(\tR\x0ecommitterEmail\x12\x12\n" +
	"\x04diff\x18\b \x01(\tR\x04diff\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xa3\x01\n" +
	"\x05Label\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x1c.matrixhub.v1alpha1.CategoryR\bcategory\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt*\x1d\n" +
	"\bFileType\x12\a\n" +
	"\x03DIR\x10\x00\x12\b\n" +
	"\x04FILE\x10\x01*G\n" +
	"\bCategory\x12\b\n" +
	"\x04TASK\x10\x00\x12\v\n" +
	"\aLIBRARY\x10\x01\x12\v\n" +
	"\aLICENSE\x10\x02\x12\f\n" +
	"\bLANGUAGE\x10\x03\x12\t\n" +
	"\x05OTHER\x10\x042\xe7\f\n" +
	"\x06Models\x12\xa0\x01\n" +
	"\x13ListModelTaskLabels\x12..matrixhub.v1alpha1.ListModelTaskLabelsRequest\x1a/.matrixhub.v1alpha1.ListModelTaskLabelsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1alpha1/models/task-labels\x12\xa6\x01\n" +
	"\x14ListModelFrameLabels\x12/.matrixhub.v1alpha1.ListModelFrameLabelsRequest\x1a0.matrixhub.v1alpha1.ListModelFrameLabelsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1alpha1/models/library-labels\x12y\n" +
	"\n" +
	"ListModels\x12%.matrixhub.v1alpha1.ListModelsRequest\x1a&.matrixhub.v1alpha1.ListModelsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1alpha1/models\x12y\n" +
	"\bGetModel\x12#.matrixhub.v1alpha1.GetModelRequest\x1a\x19.matrixhub.v1alpha1.Model\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1alpha1/models/{project}/{name}\x12\x7f\n" +
	"\vCreateModel\x12&.matrixhub.v1alpha1.CreateModelRequest\x1a'.matrixhub.v1alpha1.CreateModelResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1alpha1/models\x12\x8d\x01\n" +
	"\vDeleteModel\x12&.matrixhub.v1alpha1.DeleteModelRequest\x1a'.matrixhub.v1alpha1.DeleteModelResponse\"-\x82\xd3\xe4\x93\x02'*%/api/v1alpha1/models/{project}/{name}\x12\xac\x01\n" +
	"\x12ListModelRevisions\x12-.matrixhub.v1alpha1.ListModelRevisionsRequest\x1a..matrixhub.v1alpha1.ListModelRevisionsResponse\"7\x82\xd3\xe4\x93\x021\x12//api/v1alpha1/models/{project}/{name}/revisions\x12\xa4\x01\n" +
	"\x10ListModelCommits\x12+.matrixhub.v1alpha1.ListModelCommitsRequest\x1a,.matrixhub.v1alpha1.ListModelCommitsResponse\"5\x82\xd3\xe4\x93\x02/\x12-/api/v1alpha1/models/{project}/{name}/commits\x12\x93\x01\n" +
	"\x0eGetModelCommit\x12).matrixhub.v1alpha1.GetModelCommitRequest\x1a\x1a.matrixhub.v1alpha1.Commit\":\x82\xd3\xe4\x93\x024\x122/api/v1alpha1/models/{project}/{name}/commits/{id}\x12\x95\x01\n" +
	"\fGetModelTree\x12'.matrixhub.v1alpha1.GetModelTreeRequest\x1a(.matrixhub.v1alpha1.GetModelTreeResponse\"2\x82\xd3\xe4\x93\x02,\x12*/api/v1alpha1/models/{project}/{name}/tree\x12\x85\x01\n" +
	"\fGetModelBlob\x12'.matrixhub.v1alpha1.GetModelBlobRequest\x1a\x18.matrixhub.v1alpha1.File\"2\x82\xd3\xe4\x93\x02,\x12*/api/v1alpha1/models/{project}/{name}/blobB<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_model_proto_rawDescOnce sync.Once
	file_v1alpha1_model_proto_rawDescData []byte
)

func file_v1alpha1_model_proto_rawDescGZIP() []byte {
	file_v1alpha1_model_proto_rawDescOnce.Do(func() {
		file_v1alpha1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_model_proto_rawDesc), len(file_v1alpha1_model_proto_rawDesc)))
	})
	return file_v1alpha1_model_proto_rawDescData
}

var file_v1alpha1_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1alpha1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_v1alpha1_model_proto_goTypes = []any{
	(FileType)(0),                        // 0: matrixhub.v1alpha1.FileType
	(Category)(0),                        // 1: matrixhub.v1alpha1.Category
	(*ListModelTaskLabelsRequest)(nil),   // 2: matrixhub.v1alpha1.ListModelTaskLabelsRequest
	(*ListModelTaskLabelsResponse)(nil),  // 3: matrixhub.v1alpha1.ListModelTaskLabelsResponse
	(*ListModelFrameLabelsRequest)(nil),  // 4: matrixhub.v1alpha1.ListModelFrameLabelsRequest
	(*ListModelFrameLabelsResponse)(nil), // 5: matrixhub.v1alpha1.ListModelFrameLabelsResponse
	(*ListModelsRequest)(nil),            // 6: matrixhub.v1alpha1.ListModelsRequest
	(*ListModelsResponse)(nil),           // 7: matrixhub.v1alpha1.ListModelsResponse
	(*GetModelRequest)(nil),              // 8: matrixhub.v1alpha1.GetModelRequest
	(*CreateModelRequest)(nil),           // 9: matrixhub.v1alpha1.CreateModelRequest
	(*CreateModelResponse)(nil),          // 10: matrixhub.v1alpha1.CreateModelResponse
	(*DeleteModelRequest)(nil),           // 11: matrixhub.v1alpha1.DeleteModelRequest
	(*DeleteModelResponse)(nil),          // 12: matrixhub.v1alpha1.DeleteModelResponse
	(*ListModelRevisionsRequest)(nil),    // 13: matrixhub.v1alpha1.ListModelRevisionsRequest
	(*ListModelRevisionsResponse)(nil),   // 14: matrixhub.v1alpha1.ListModelRevisionsResponse
	(*Revisions)(nil),                    // 15: matrixhub.v1alpha1.Revisions
	(*ListModelCommitsRequest)(nil),      // 16: matrixhub.v1alpha1.ListModelCommitsRequest
	(*ListModelCommitsResponse)(nil),     // 17: matrixhub.v1alpha1.ListModelCommitsResponse
	(*GetModelCommitRequest)(nil),        // 18: matrixhub.v1alpha1.GetModelCommitRequest
	(*GetModelTreeRequest)(nil),          // 19: matrixhub.v1alpha1.GetModelTreeRequest
	(*File)(nil),                         // 20: matrixhub.v1alpha1.File
	(*GetModelTreeResponse)(nil),         // 21: matrixhub.v1alpha1.GetModelTreeResponse
	(*GetModelBlobRequest)(nil),          // 22: matrixhub.v1alpha1.GetModelBlobRequest
	(*Model)(nil),                        // 23: matrixhub.v1alpha1.Model
	(*CloneUrls)(nil),                    // 24: matrixhub.v1alpha1.CloneUrls
	(*Revision)(nil),                     // 25: matrixhub.v1alpha1.Revision
	(*Commit)(nil),                       // 26: matrixhub.v1alpha1.Commit
	(*Label)(nil),                        // 27: matrixhub.v1alpha1.Label
	(*Pagination)(nil),                   // 28: matrixhub.v1alpha1.Pagination
}
var file_v1alpha1_model_proto_depIdxs = []int32{
	27, // 0: matrixhub.v1alpha1.ListModelTaskLabelsResponse.items:type_name -> matrixhub.v1alpha1.Label
	27, // 1: matrixhub.v1alpha1.ListModelFrameLabelsResponse.items:type_name -> matrixhub.v1alpha1.Label
	23, // 2: matrixhub.v1alpha1.ListModelsResponse.items:type_name -> matrixhub.v1alpha1.Model
	28, // 3: matrixhub.v1alpha1.ListModelsResponse.pagination:type_name -> matrixhub.v1alpha1.Pagination
	15, // 4: matrixhub.v1alpha1.ListModelRevisionsResponse.items:type_name -> matrixhub.v1alpha1.Revisions
	25, // 5: matrixhub.v1alpha1.Revisions.branches:type_name -> matrixhub.v1alpha1.Revision
	25, // 6: matrixhub.v1alpha1.Revisions.tags:type_name -> matrixhub.v1alpha1.Revision
	26, // 7: matrixhub.v1alpha1.ListModelCommitsResponse.items:type_name -> matrixhub.v1alpha1.Commit
	28, // 8: matrixhub.v1alpha1.ListModelCommitsResponse.pagination:type_name -> matrixhub.v1alpha1.Pagination
	0,  // 9: matrixhub.v1alpha1.File.type:type_name -> matrixhub.v1alpha1.FileType
	26, // 10: matrixhub.v1alpha1.File.commit:type_name -> matrixhub.v1alpha1.Commit
	20, // 11: matrixhub.v1alpha1.GetModelTreeResponse.items:type_name -> matrixhub.v1alpha1.File
	24, // 12: matrixhub.v1alpha1.Model.clone_urls:type_name -> matrixhub.v1alpha1.CloneUrls
	27, // 13: matrixhub.v1alpha1.Model.labels:type_name -> matrixhub.v1alpha1.Label
	1,  // 14: matrixhub.v1alpha1.Label.category:type_name -> matrixhub.v1alpha1.Category
	2,  // 15: matrixhub.v1alpha1.Models.ListModelTaskLabels:input_type -> matrixhub.v1alpha1.ListModelTaskLabelsRequest
	4,  // 16: matrixhub.v1alpha1.Models.ListModelFrameLabels:input_type -> matrixhub.v1alpha1.ListModelFrameLabelsRequest
	6,  // 17: matrixhub.v1alpha1.Models.ListModels:input_type -> matrixhub.v1alpha1.ListModelsRequest
	8,  // 18: matrixhub.v1alpha1.Models.GetModel:input_type -> matrixhub.v1alpha1.GetModelRequest
	9,  // 19: matrixhub.v1alpha1.Models.CreateModel:input_type -> matrixhub.v1alpha1.CreateModelRequest
	11, // 20: matrixhub.v1alpha1.Models.DeleteModel:input_type -> matrixhub.v1alpha1.DeleteModelRequest
	13, // 21: matrixhub.v1alpha1.Models.ListModelRevisions:input_type -> matrixhub.v1alpha1.ListModelRevisionsRequest
	16, // 22: matrixhub.v1alpha1.Models.ListModelCommits:input_type -> matrixhub.v1alpha1.ListModelCommitsRequest
	18, // 23: matrixhub.v1alpha1.Models.GetModelCommit:input_type -> matrixhub.v1alpha1.GetModelCommitRequest
	19, // 24: matrixhub.v1alpha1.Models.GetModelTree:input_type -> matrixhub.v1alpha1.GetModelTreeRequest
	22, // 25: matrixhub.v1alpha1.Models.GetModelBlob:input_type -> matrixhub.v1alpha1.GetModelBlobRequest
	3,  // 26: matrixhub.v1alpha1.Models.ListModelTaskLabels:output_type -> matrixhub.v1alpha1.ListModelTaskLabelsResponse
	5,  // 27: matrixhub.v1alpha1.Models.ListModelFrameLabels:output_type -> matrixhub.v1alpha1.ListModelFrameLabelsResponse
	7,  // 28: matrixhub.v1alpha1.Models.ListModels:output_type -> matrixhub.v1alpha1.ListModelsResponse
	23, // 29: matrixhub.v1alpha1.Models.GetModel:output_type -> matrixhub.v1alpha1.Model
	10, // 30: matrixhub.v1alpha1.Models.CreateModel:output_type -> matrixhub.v1alpha1.CreateModelResponse
	12, // 31: matrixhub.v1alpha1.Models.DeleteModel:output_type -> matrixhub.v1alpha1.DeleteModelResponse
	14, // 32: matrixhub.v1alpha1.Models.ListModelRevisions:output_type -> matrixhub.v1alpha1.ListModelRevisionsResponse
	17, // 33: matrixhub.v1alpha1.Models.ListModelCommits:output_type -> matrixhub.v1alpha1.ListModelCommitsResponse
	26, // 34: matrixhub.v1alpha1.Models.GetModelCommit:output_type -> matrixhub.v1alpha1.Commit
	21, // 35: matrixhub.v1alpha1.Models.GetModelTree:output_type -> matrixhub.v1alpha1.GetModelTreeResponse
	20, // 36: matrixhub.v1alpha1.Models.GetModelBlob:output_type -> matrixhub.v1alpha1.File
	26, // [26:37] is the sub-list for method output_type
	15, // [15:26] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1alpha1_model_proto_init() }
func file_v1alpha1_model_proto_init() {
	if File_v1alpha1_model_proto != nil {
		return
	}
	file_v1alpha1_utils_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_model_proto_rawDesc), len(file_v1alpha1_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_model_proto_goTypes,
		DependencyIndexes: file_v1alpha1_model_proto_depIdxs,
		EnumInfos:         file_v1alpha1_model_proto_enumTypes,
		MessageInfos:      file_v1alpha1_model_proto_msgTypes,
	}.Build()
	File_v1alpha1_model_proto = out.File
	file_v1alpha1_model_proto_goTypes = nil
	file_v1alpha1_model_proto_depIdxs = nil
}
