// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/model.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListModelTaskLabelsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelTaskLabelsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelTaskLabelsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelTaskLabelsRequestMultiError, or nil if none found.
func (m *ListModelTaskLabelsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelTaskLabelsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListModelTaskLabelsRequestMultiError(errors)
	}

	return nil
}

// ListModelTaskLabelsRequestMultiError is an error wrapping multiple
// validation errors returned by ListModelTaskLabelsRequest.ValidateAll() if
// the designated constraints aren't met.
type ListModelTaskLabelsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelTaskLabelsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelTaskLabelsRequestMultiError) AllErrors() []error { return m }

// ListModelTaskLabelsRequestValidationError is the validation error returned
// by ListModelTaskLabelsRequest.Validate if the designated constraints aren't met.
type ListModelTaskLabelsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelTaskLabelsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelTaskLabelsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelTaskLabelsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelTaskLabelsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelTaskLabelsRequestValidationError) ErrorName() string {
	return "ListModelTaskLabelsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelTaskLabelsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelTaskLabelsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelTaskLabelsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelTaskLabelsRequestValidationError{}

// Validate checks the field values on ListModelTaskLabelsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelTaskLabelsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelTaskLabelsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelTaskLabelsResponseMultiError, or nil if none found.
func (m *ListModelTaskLabelsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelTaskLabelsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListModelTaskLabelsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListModelTaskLabelsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListModelTaskLabelsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListModelTaskLabelsResponseMultiError(errors)
	}

	return nil
}

// ListModelTaskLabelsResponseMultiError is an error wrapping multiple
// validation errors returned by ListModelTaskLabelsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListModelTaskLabelsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelTaskLabelsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelTaskLabelsResponseMultiError) AllErrors() []error { return m }

// ListModelTaskLabelsResponseValidationError is the validation error returned
// by ListModelTaskLabelsResponse.Validate if the designated constraints
// aren't met.
type ListModelTaskLabelsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelTaskLabelsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelTaskLabelsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelTaskLabelsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelTaskLabelsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelTaskLabelsResponseValidationError) ErrorName() string {
	return "ListModelTaskLabelsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelTaskLabelsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelTaskLabelsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelTaskLabelsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelTaskLabelsResponseValidationError{}

// Validate checks the field values on ListModelFrameLabelsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelFrameLabelsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelFrameLabelsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelFrameLabelsRequestMultiError, or nil if none found.
func (m *ListModelFrameLabelsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelFrameLabelsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListModelFrameLabelsRequestMultiError(errors)
	}

	return nil
}

// ListModelFrameLabelsRequestMultiError is an error wrapping multiple
// validation errors returned by ListModelFrameLabelsRequest.ValidateAll() if
// the designated constraints aren't met.
type ListModelFrameLabelsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelFrameLabelsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelFrameLabelsRequestMultiError) AllErrors() []error { return m }

// ListModelFrameLabelsRequestValidationError is the validation error returned
// by ListModelFrameLabelsRequest.Validate if the designated constraints
// aren't met.
type ListModelFrameLabelsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelFrameLabelsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelFrameLabelsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelFrameLabelsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelFrameLabelsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelFrameLabelsRequestValidationError) ErrorName() string {
	return "ListModelFrameLabelsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelFrameLabelsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelFrameLabelsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelFrameLabelsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelFrameLabelsRequestValidationError{}

// Validate checks the field values on ListModelFrameLabelsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelFrameLabelsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelFrameLabelsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelFrameLabelsResponseMultiError, or nil if none found.
func (m *ListModelFrameLabelsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelFrameLabelsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListModelFrameLabelsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListModelFrameLabelsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListModelFrameLabelsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListModelFrameLabelsResponseMultiError(errors)
	}

	return nil
}

// ListModelFrameLabelsResponseMultiError is an error wrapping multiple
// validation errors returned by ListModelFrameLabelsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListModelFrameLabelsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelFrameLabelsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelFrameLabelsResponseMultiError) AllErrors() []error { return m }

// ListModelFrameLabelsResponseValidationError is the validation error returned
// by ListModelFrameLabelsResponse.Validate if the designated constraints
// aren't met.
type ListModelFrameLabelsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelFrameLabelsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelFrameLabelsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelFrameLabelsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelFrameLabelsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelFrameLabelsResponseValidationError) ErrorName() string {
	return "ListModelFrameLabelsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelFrameLabelsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelFrameLabelsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelFrameLabelsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelFrameLabelsResponseValidationError{}

// Validate checks the field values on ListModelsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListModelsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelsRequestMultiError, or nil if none found.
func (m *ListModelsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Search

	// no validation rules for Sort

	// no validation rules for Project

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for Popular

	if len(errors) > 0 {
		return ListModelsRequestMultiError(errors)
	}

	return nil
}

// ListModelsRequestMultiError is an error wrapping multiple validation errors
// returned by ListModelsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListModelsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelsRequestMultiError) AllErrors() []error { return m }

// ListModelsRequestValidationError is the validation error returned by
// ListModelsRequest.Validate if the designated constraints aren't met.
type ListModelsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelsRequestValidationError) ErrorName() string {
	return "ListModelsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelsRequestValidationError{}

// Validate checks the field values on ListModelsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelsResponseMultiError, or nil if none found.
func (m *ListModelsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListModelsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListModelsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListModelsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListModelsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListModelsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListModelsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListModelsResponseMultiError(errors)
	}

	return nil
}

// ListModelsResponseMultiError is an error wrapping multiple validation errors
// returned by ListModelsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListModelsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelsResponseMultiError) AllErrors() []error { return m }

// ListModelsResponseValidationError is the validation error returned by
// ListModelsResponse.Validate if the designated constraints aren't met.
type ListModelsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelsResponseValidationError) ErrorName() string {
	return "ListModelsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelsResponseValidationError{}

// Validate checks the field values on GetModelRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetModelRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelRequestMultiError, or nil if none found.
func (m *GetModelRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := GetModelRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := GetModelRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetModelRequestMultiError(errors)
	}

	return nil
}

// GetModelRequestMultiError is an error wrapping multiple validation errors
// returned by GetModelRequest.ValidateAll() if the designated constraints
// aren't met.
type GetModelRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelRequestMultiError) AllErrors() []error { return m }

// GetModelRequestValidationError is the validation error returned by
// GetModelRequest.Validate if the designated constraints aren't met.
type GetModelRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelRequestValidationError) ErrorName() string { return "GetModelRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetModelRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelRequestValidationError{}

// Validate checks the field values on CreateModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateModelRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateModelRequestMultiError, or nil if none found.
func (m *CreateModelRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateModelRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := CreateModelRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CreateModelRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateModelRequestMultiError(errors)
	}

	return nil
}

// CreateModelRequestMultiError is an error wrapping multiple validation errors
// returned by CreateModelRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateModelRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateModelRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateModelRequestMultiError) AllErrors() []error { return m }

// CreateModelRequestValidationError is the validation error returned by
// CreateModelRequest.Validate if the designated constraints aren't met.
type CreateModelRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateModelRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateModelRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateModelRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateModelRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateModelRequestValidationError) ErrorName() string {
	return "CreateModelRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateModelRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateModelRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateModelRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateModelRequestValidationError{}

// Validate checks the field values on CreateModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateModelResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateModelResponseMultiError, or nil if none found.
func (m *CreateModelResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateModelResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CreateModelResponseMultiError(errors)
	}

	return nil
}

// CreateModelResponseMultiError is an error wrapping multiple validation
// errors returned by CreateModelResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateModelResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateModelResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateModelResponseMultiError) AllErrors() []error { return m }

// CreateModelResponseValidationError is the validation error returned by
// CreateModelResponse.Validate if the designated constraints aren't met.
type CreateModelResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateModelResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateModelResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateModelResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateModelResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateModelResponseValidationError) ErrorName() string {
	return "CreateModelResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateModelResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateModelResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateModelResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateModelResponseValidationError{}

// Validate checks the field values on DeleteModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteModelRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteModelRequestMultiError, or nil if none found.
func (m *DeleteModelRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteModelRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := DeleteModelRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := DeleteModelRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteModelRequestMultiError(errors)
	}

	return nil
}

// DeleteModelRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteModelRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteModelRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteModelRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteModelRequestMultiError) AllErrors() []error { return m }

// DeleteModelRequestValidationError is the validation error returned by
// DeleteModelRequest.Validate if the designated constraints aren't met.
type DeleteModelRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteModelRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteModelRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteModelRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteModelRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteModelRequestValidationError) ErrorName() string {
	return "DeleteModelRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteModelRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteModelRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteModelRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteModelRequestValidationError{}

// Validate checks the field values on DeleteModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteModelResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteModelResponseMultiError, or nil if none found.
func (m *DeleteModelResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteModelResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteModelResponseMultiError(errors)
	}

	return nil
}

// DeleteModelResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteModelResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteModelResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteModelResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteModelResponseMultiError) AllErrors() []error { return m }

// DeleteModelResponseValidationError is the validation error returned by
// DeleteModelResponse.Validate if the designated constraints aren't met.
type DeleteModelResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteModelResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteModelResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteModelResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteModelResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteModelResponseValidationError) ErrorName() string {
	return "DeleteModelResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteModelResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteModelResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteModelResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteModelResponseValidationError{}

// Validate checks the field values on ListModelRevisionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelRevisionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelRevisionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelRevisionsRequestMultiError, or nil if none found.
func (m *ListModelRevisionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelRevisionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := ListModelRevisionsRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := ListModelRevisionsRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListModelRevisionsRequestMultiError(errors)
	}

	return nil
}

// ListModelRevisionsRequestMultiError is an error wrapping multiple validation
// errors returned by ListModelRevisionsRequest.ValidateAll() if the
// designated constraints aren't met.
type ListModelRevisionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelRevisionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelRevisionsRequestMultiError) AllErrors() []error { return m }

// ListModelRevisionsRequestValidationError is the validation error returned by
// ListModelRevisionsRequest.Validate if the designated constraints aren't met.
type ListModelRevisionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelRevisionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelRevisionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelRevisionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelRevisionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelRevisionsRequestValidationError) ErrorName() string {
	return "ListModelRevisionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelRevisionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelRevisionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelRevisionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelRevisionsRequestValidationError{}

// Validate checks the field values on ListModelRevisionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelRevisionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelRevisionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelRevisionsResponseMultiError, or nil if none found.
func (m *ListModelRevisionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelRevisionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetItems()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListModelRevisionsResponseValidationError{
					field:  "Items",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListModelRevisionsResponseValidationError{
					field:  "Items",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetItems()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListModelRevisionsResponseValidationError{
				field:  "Items",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListModelRevisionsResponseMultiError(errors)
	}

	return nil
}

// ListModelRevisionsResponseMultiError is an error wrapping multiple
// validation errors returned by ListModelRevisionsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListModelRevisionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelRevisionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelRevisionsResponseMultiError) AllErrors() []error { return m }

// ListModelRevisionsResponseValidationError is the validation error returned
// by ListModelRevisionsResponse.Validate if the designated constraints aren't met.
type ListModelRevisionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelRevisionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelRevisionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelRevisionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelRevisionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelRevisionsResponseValidationError) ErrorName() string {
	return "ListModelRevisionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelRevisionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelRevisionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelRevisionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelRevisionsResponseValidationError{}

// Validate checks the field values on Revisions with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Revisions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Revisions with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RevisionsMultiError, or nil
// if none found.
func (m *Revisions) ValidateAll() error {
	return m.validate(true)
}

func (m *Revisions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBranches() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RevisionsValidationError{
						field:  fmt.Sprintf("Branches[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RevisionsValidationError{
						field:  fmt.Sprintf("Branches[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RevisionsValidationError{
					field:  fmt.Sprintf("Branches[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetTags() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RevisionsValidationError{
						field:  fmt.Sprintf("Tags[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RevisionsValidationError{
						field:  fmt.Sprintf("Tags[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RevisionsValidationError{
					field:  fmt.Sprintf("Tags[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return RevisionsMultiError(errors)
	}

	return nil
}

// RevisionsMultiError is an error wrapping multiple validation errors returned
// by Revisions.ValidateAll() if the designated constraints aren't met.
type RevisionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevisionsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevisionsMultiError) AllErrors() []error { return m }

// RevisionsValidationError is the validation error returned by
// Revisions.Validate if the designated constraints aren't met.
type RevisionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevisionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevisionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevisionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevisionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevisionsValidationError) ErrorName() string { return "RevisionsValidationError" }

// Error satisfies the builtin error interface
func (e RevisionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevisions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevisionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevisionsValidationError{}

// Validate checks the field values on ListModelCommitsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelCommitsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelCommitsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelCommitsRequestMultiError, or nil if none found.
func (m *ListModelCommitsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelCommitsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := ListModelCommitsRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := ListModelCommitsRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Revision

	// no validation rules for Diff

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListModelCommitsRequestMultiError(errors)
	}

	return nil
}

// ListModelCommitsRequestMultiError is an error wrapping multiple validation
// errors returned by ListModelCommitsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListModelCommitsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelCommitsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelCommitsRequestMultiError) AllErrors() []error { return m }

// ListModelCommitsRequestValidationError is the validation error returned by
// ListModelCommitsRequest.Validate if the designated constraints aren't met.
type ListModelCommitsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelCommitsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelCommitsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelCommitsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelCommitsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelCommitsRequestValidationError) ErrorName() string {
	return "ListModelCommitsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelCommitsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelCommitsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelCommitsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelCommitsRequestValidationError{}

// Validate checks the field values on ListModelCommitsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModelCommitsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModelCommitsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModelCommitsResponseMultiError, or nil if none found.
func (m *ListModelCommitsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModelCommitsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListModelCommitsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListModelCommitsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListModelCommitsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListModelCommitsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListModelCommitsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListModelCommitsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListModelCommitsResponseMultiError(errors)
	}

	return nil
}

// ListModelCommitsResponseMultiError is an error wrapping multiple validation
// errors returned by ListModelCommitsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListModelCommitsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModelCommitsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModelCommitsResponseMultiError) AllErrors() []error { return m }

// ListModelCommitsResponseValidationError is the validation error returned by
// ListModelCommitsResponse.Validate if the designated constraints aren't met.
type ListModelCommitsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModelCommitsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModelCommitsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModelCommitsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModelCommitsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModelCommitsResponseValidationError) ErrorName() string {
	return "ListModelCommitsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListModelCommitsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModelCommitsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModelCommitsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModelCommitsResponseValidationError{}

// Validate checks the field values on GetModelCommitRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelCommitRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelCommitRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelCommitRequestMultiError, or nil if none found.
func (m *GetModelCommitRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelCommitRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := GetModelCommitRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := GetModelCommitRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := GetModelCommitRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetModelCommitRequestMultiError(errors)
	}

	return nil
}

// GetModelCommitRequestMultiError is an error wrapping multiple validation
// errors returned by GetModelCommitRequest.ValidateAll() if the designated
// constraints aren't met.
type GetModelCommitRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelCommitRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelCommitRequestMultiError) AllErrors() []error { return m }

// GetModelCommitRequestValidationError is the validation error returned by
// GetModelCommitRequest.Validate if the designated constraints aren't met.
type GetModelCommitRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelCommitRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelCommitRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelCommitRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelCommitRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelCommitRequestValidationError) ErrorName() string {
	return "GetModelCommitRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelCommitRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelCommitRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelCommitRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelCommitRequestValidationError{}

// Validate checks the field values on GetModelTreeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelTreeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelTreeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelTreeRequestMultiError, or nil if none found.
func (m *GetModelTreeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelTreeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := GetModelTreeRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := GetModelTreeRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Revision

	// no validation rules for Path

	if len(errors) > 0 {
		return GetModelTreeRequestMultiError(errors)
	}

	return nil
}

// GetModelTreeRequestMultiError is an error wrapping multiple validation
// errors returned by GetModelTreeRequest.ValidateAll() if the designated
// constraints aren't met.
type GetModelTreeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelTreeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelTreeRequestMultiError) AllErrors() []error { return m }

// GetModelTreeRequestValidationError is the validation error returned by
// GetModelTreeRequest.Validate if the designated constraints aren't met.
type GetModelTreeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelTreeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelTreeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelTreeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelTreeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelTreeRequestValidationError) ErrorName() string {
	return "GetModelTreeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelTreeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelTreeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelTreeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelTreeRequestValidationError{}

// Validate checks the field values on File with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *File) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on File with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in FileMultiError, or nil if none found.
func (m *File) ValidateAll() error {
	return m.validate(true)
}

func (m *File) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Type

	// no validation rules for Path

	// no validation rules for Size

	// no validation rules for Lfs

	// no validation rules for Sha256

	if all {
		switch v := interface{}(m.GetCommit()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FileValidationError{
					field:  "Commit",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FileValidationError{
					field:  "Commit",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCommit()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FileValidationError{
				field:  "Commit",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Url

	if len(errors) > 0 {
		return FileMultiError(errors)
	}

	return nil
}

// FileMultiError is an error wrapping multiple validation errors returned by
// File.ValidateAll() if the designated constraints aren't met.
type FileMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileMultiError) AllErrors() []error { return m }

// FileValidationError is the validation error returned by File.Validate if the
// designated constraints aren't met.
type FileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileValidationError) ErrorName() string { return "FileValidationError" }

// Error satisfies the builtin error interface
func (e FileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileValidationError{}

// Validate checks the field values on GetModelTreeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelTreeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelTreeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelTreeResponseMultiError, or nil if none found.
func (m *GetModelTreeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelTreeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetModelTreeResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetModelTreeResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetModelTreeResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetModelTreeResponseMultiError(errors)
	}

	return nil
}

// GetModelTreeResponseMultiError is an error wrapping multiple validation
// errors returned by GetModelTreeResponse.ValidateAll() if the designated
// constraints aren't met.
type GetModelTreeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelTreeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelTreeResponseMultiError) AllErrors() []error { return m }

// GetModelTreeResponseValidationError is the validation error returned by
// GetModelTreeResponse.Validate if the designated constraints aren't met.
type GetModelTreeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelTreeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelTreeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelTreeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelTreeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelTreeResponseValidationError) ErrorName() string {
	return "GetModelTreeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelTreeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelTreeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelTreeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelTreeResponseValidationError{}

// Validate checks the field values on GetModelBlobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModelBlobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModelBlobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModelBlobRequestMultiError, or nil if none found.
func (m *GetModelBlobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModelBlobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProject()) < 1 {
		err := GetModelBlobRequestValidationError{
			field:  "Project",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := GetModelBlobRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Revision

	// no validation rules for Path

	if len(errors) > 0 {
		return GetModelBlobRequestMultiError(errors)
	}

	return nil
}

// GetModelBlobRequestMultiError is an error wrapping multiple validation
// errors returned by GetModelBlobRequest.ValidateAll() if the designated
// constraints aren't met.
type GetModelBlobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModelBlobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModelBlobRequestMultiError) AllErrors() []error { return m }

// GetModelBlobRequestValidationError is the validation error returned by
// GetModelBlobRequest.Validate if the designated constraints aren't met.
type GetModelBlobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModelBlobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModelBlobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModelBlobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModelBlobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModelBlobRequestValidationError) ErrorName() string {
	return "GetModelBlobRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetModelBlobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModelBlobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModelBlobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModelBlobRequestValidationError{}

// Validate checks the field values on Model with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Model) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Model with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ModelMultiError, or nil if none found.
func (m *Model) ValidateAll() error {
	return m.validate(true)
}

func (m *Model) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Nickname

	// no validation rules for DefaultBranch

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if all {
		switch v := interface{}(m.GetCloneUrls()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelValidationError{
					field:  "CloneUrls",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelValidationError{
					field:  "CloneUrls",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCloneUrls()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelValidationError{
				field:  "CloneUrls",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetLabels() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelValidationError{
						field:  fmt.Sprintf("Labels[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelValidationError{
						field:  fmt.Sprintf("Labels[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelValidationError{
					field:  fmt.Sprintf("Labels[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Project

	// no validation rules for ReadmeContent

	// no validation rules for Size

	// no validation rules for ParameterCount

	if len(errors) > 0 {
		return ModelMultiError(errors)
	}

	return nil
}

// ModelMultiError is an error wrapping multiple validation errors returned by
// Model.ValidateAll() if the designated constraints aren't met.
type ModelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelMultiError) AllErrors() []error { return m }

// ModelValidationError is the validation error returned by Model.Validate if
// the designated constraints aren't met.
type ModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelValidationError) ErrorName() string { return "ModelValidationError" }

// Error satisfies the builtin error interface
func (e ModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelValidationError{}

// Validate checks the field values on CloneUrls with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CloneUrls) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CloneUrls with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CloneUrlsMultiError, or nil
// if none found.
func (m *CloneUrls) ValidateAll() error {
	return m.validate(true)
}

func (m *CloneUrls) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SshUrl

	// no validation rules for HttpUrl

	if len(errors) > 0 {
		return CloneUrlsMultiError(errors)
	}

	return nil
}

// CloneUrlsMultiError is an error wrapping multiple validation errors returned
// by CloneUrls.ValidateAll() if the designated constraints aren't met.
type CloneUrlsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CloneUrlsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CloneUrlsMultiError) AllErrors() []error { return m }

// CloneUrlsValidationError is the validation error returned by
// CloneUrls.Validate if the designated constraints aren't met.
type CloneUrlsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CloneUrlsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CloneUrlsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CloneUrlsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CloneUrlsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CloneUrlsValidationError) ErrorName() string { return "CloneUrlsValidationError" }

// Error satisfies the builtin error interface
func (e CloneUrlsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCloneUrls.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CloneUrlsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CloneUrlsValidationError{}

// Validate checks the field values on Revision with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Revision) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Revision with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RevisionMultiError, or nil
// if none found.
func (m *Revision) ValidateAll() error {
	return m.validate(true)
}

func (m *Revision) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return RevisionMultiError(errors)
	}

	return nil
}

// RevisionMultiError is an error wrapping multiple validation errors returned
// by Revision.ValidateAll() if the designated constraints aren't met.
type RevisionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevisionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevisionMultiError) AllErrors() []error { return m }

// RevisionValidationError is the validation error returned by
// Revision.Validate if the designated constraints aren't met.
type RevisionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevisionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevisionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevisionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevisionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevisionValidationError) ErrorName() string { return "RevisionValidationError" }

// Error satisfies the builtin error interface
func (e RevisionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevision.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevisionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevisionValidationError{}

// Validate checks the field values on Commit with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Commit) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Commit with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CommitMultiError, or nil if none found.
func (m *Commit) ValidateAll() error {
	return m.validate(true)
}

func (m *Commit) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Message

	// no validation rules for AuthorName

	// no validation rules for AuthorEmail

	// no validation rules for AuthorDate

	// no validation rules for CommitterName

	// no validation rules for CommitterEmail

	// no validation rules for Diff

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return CommitMultiError(errors)
	}

	return nil
}

// CommitMultiError is an error wrapping multiple validation errors returned by
// Commit.ValidateAll() if the designated constraints aren't met.
type CommitMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommitMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommitMultiError) AllErrors() []error { return m }

// CommitValidationError is the validation error returned by Commit.Validate if
// the designated constraints aren't met.
type CommitValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommitValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommitValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommitValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommitValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommitValidationError) ErrorName() string { return "CommitValidationError" }

// Error satisfies the builtin error interface
func (e CommitValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommit.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommitValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommitValidationError{}

// Validate checks the field values on Label with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Label) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Label with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LabelMultiError, or nil if none found.
func (m *Label) ValidateAll() error {
	return m.validate(true)
}

func (m *Label) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Category

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return LabelMultiError(errors)
	}

	return nil
}

// LabelMultiError is an error wrapping multiple validation errors returned by
// Label.ValidateAll() if the designated constraints aren't met.
type LabelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LabelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LabelMultiError) AllErrors() []error { return m }

// LabelValidationError is the validation error returned by Label.Validate if
// the designated constraints aren't met.
type LabelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LabelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LabelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LabelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LabelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LabelValidationError) ErrorName() string { return "LabelValidationError" }

// Error satisfies the builtin error interface
func (e LabelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLabel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LabelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LabelValidationError{}
