// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: v1alpha1/model.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Models_ListModelTaskLabels_FullMethodName  = "/matrixhub.v1alpha1.Models/ListModelTaskLabels"
	Models_ListModelFrameLabels_FullMethodName = "/matrixhub.v1alpha1.Models/ListModelFrameLabels"
	Models_ListModels_FullMethodName           = "/matrixhub.v1alpha1.Models/ListModels"
	Models_GetModel_FullMethodName             = "/matrixhub.v1alpha1.Models/GetModel"
	Models_CreateModel_FullMethodName          = "/matrixhub.v1alpha1.Models/CreateModel"
	Models_DeleteModel_FullMethodName          = "/matrixhub.v1alpha1.Models/DeleteModel"
	Models_ListModelRevisions_FullMethodName   = "/matrixhub.v1alpha1.Models/ListModelRevisions"
	Models_ListModelCommits_FullMethodName     = "/matrixhub.v1alpha1.Models/ListModelCommits"
	Models_GetModelCommit_FullMethodName       = "/matrixhub.v1alpha1.Models/GetModelCommit"
	Models_GetModelTree_FullMethodName         = "/matrixhub.v1alpha1.Models/GetModelTree"
	Models_GetModelBlob_FullMethodName         = "/matrixhub.v1alpha1.Models/GetModelBlob"
)

// ModelsClient is the client API for Models service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelsClient interface {
	ListModelTaskLabels(ctx context.Context, in *ListModelTaskLabelsRequest, opts ...grpc.CallOption) (*ListModelTaskLabelsResponse, error)
	ListModelFrameLabels(ctx context.Context, in *ListModelFrameLabelsRequest, opts ...grpc.CallOption) (*ListModelFrameLabelsResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*Model, error)
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
	ListModelRevisions(ctx context.Context, in *ListModelRevisionsRequest, opts ...grpc.CallOption) (*ListModelRevisionsResponse, error)
	ListModelCommits(ctx context.Context, in *ListModelCommitsRequest, opts ...grpc.CallOption) (*ListModelCommitsResponse, error)
	GetModelCommit(ctx context.Context, in *GetModelCommitRequest, opts ...grpc.CallOption) (*Commit, error)
	GetModelTree(ctx context.Context, in *GetModelTreeRequest, opts ...grpc.CallOption) (*GetModelTreeResponse, error)
	GetModelBlob(ctx context.Context, in *GetModelBlobRequest, opts ...grpc.CallOption) (*File, error)
}

type modelsClient struct {
	cc grpc.ClientConnInterface
}

func NewModelsClient(cc grpc.ClientConnInterface) ModelsClient {
	return &modelsClient{cc}
}

func (c *modelsClient) ListModelTaskLabels(ctx context.Context, in *ListModelTaskLabelsRequest, opts ...grpc.CallOption) (*ListModelTaskLabelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelTaskLabelsResponse)
	err := c.cc.Invoke(ctx, Models_ListModelTaskLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) ListModelFrameLabels(ctx context.Context, in *ListModelFrameLabelsRequest, opts ...grpc.CallOption) (*ListModelFrameLabelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelFrameLabelsResponse)
	err := c.cc.Invoke(ctx, Models_ListModelFrameLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, Models_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*Model, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Model)
	err := c.cc.Invoke(ctx, Models_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateModelResponse)
	err := c.cc.Invoke(ctx, Models_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, Models_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) ListModelRevisions(ctx context.Context, in *ListModelRevisionsRequest, opts ...grpc.CallOption) (*ListModelRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelRevisionsResponse)
	err := c.cc.Invoke(ctx, Models_ListModelRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) ListModelCommits(ctx context.Context, in *ListModelCommitsRequest, opts ...grpc.CallOption) (*ListModelCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelCommitsResponse)
	err := c.cc.Invoke(ctx, Models_ListModelCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) GetModelCommit(ctx context.Context, in *GetModelCommitRequest, opts ...grpc.CallOption) (*Commit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Commit)
	err := c.cc.Invoke(ctx, Models_GetModelCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) GetModelTree(ctx context.Context, in *GetModelTreeRequest, opts ...grpc.CallOption) (*GetModelTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelTreeResponse)
	err := c.cc.Invoke(ctx, Models_GetModelTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelsClient) GetModelBlob(ctx context.Context, in *GetModelBlobRequest, opts ...grpc.CallOption) (*File, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(File)
	err := c.cc.Invoke(ctx, Models_GetModelBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelsServer is the server API for Models service.
// All implementations should embed UnimplementedModelsServer
// for forward compatibility.
type ModelsServer interface {
	ListModelTaskLabels(context.Context, *ListModelTaskLabelsRequest) (*ListModelTaskLabelsResponse, error)
	ListModelFrameLabels(context.Context, *ListModelFrameLabelsRequest) (*ListModelFrameLabelsResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	GetModel(context.Context, *GetModelRequest) (*Model, error)
	CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	ListModelRevisions(context.Context, *ListModelRevisionsRequest) (*ListModelRevisionsResponse, error)
	ListModelCommits(context.Context, *ListModelCommitsRequest) (*ListModelCommitsResponse, error)
	GetModelCommit(context.Context, *GetModelCommitRequest) (*Commit, error)
	GetModelTree(context.Context, *GetModelTreeRequest) (*GetModelTreeResponse, error)
	GetModelBlob(context.Context, *GetModelBlobRequest) (*File, error)
}

// UnimplementedModelsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelsServer struct{}

func (UnimplementedModelsServer) ListModelTaskLabels(context.Context, *ListModelTaskLabelsRequest) (*ListModelTaskLabelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModelTaskLabels not implemented")
}
func (UnimplementedModelsServer) ListModelFrameLabels(context.Context, *ListModelFrameLabelsRequest) (*ListModelFrameLabelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModelFrameLabels not implemented")
}
func (UnimplementedModelsServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelsServer) GetModel(context.Context, *GetModelRequest) (*Model, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedModelsServer) CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedModelsServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedModelsServer) ListModelRevisions(context.Context, *ListModelRevisionsRequest) (*ListModelRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModelRevisions not implemented")
}
func (UnimplementedModelsServer) ListModelCommits(context.Context, *ListModelCommitsRequest) (*ListModelCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModelCommits not implemented")
}
func (UnimplementedModelsServer) GetModelCommit(context.Context, *GetModelCommitRequest) (*Commit, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelCommit not implemented")
}
func (UnimplementedModelsServer) GetModelTree(context.Context, *GetModelTreeRequest) (*GetModelTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelTree not implemented")
}
func (UnimplementedModelsServer) GetModelBlob(context.Context, *GetModelBlobRequest) (*File, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelBlob not implemented")
}
func (UnimplementedModelsServer) testEmbeddedByValue() {}

// UnsafeModelsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelsServer will
// result in compilation errors.
type UnsafeModelsServer interface {
	mustEmbedUnimplementedModelsServer()
}

func RegisterModelsServer(s grpc.ServiceRegistrar, srv ModelsServer) {
	// If the following call panics, it indicates UnimplementedModelsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Models_ServiceDesc, srv)
}

func _Models_ListModelTaskLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelTaskLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).ListModelTaskLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_ListModelTaskLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).ListModelTaskLabels(ctx, req.(*ListModelTaskLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_ListModelFrameLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelFrameLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).ListModelFrameLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_ListModelFrameLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).ListModelFrameLabels(ctx, req.(*ListModelFrameLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_ListModelRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).ListModelRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_ListModelRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).ListModelRevisions(ctx, req.(*ListModelRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_ListModelCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).ListModelCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_ListModelCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).ListModelCommits(ctx, req.(*ListModelCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_GetModelCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).GetModelCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_GetModelCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).GetModelCommit(ctx, req.(*GetModelCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_GetModelTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).GetModelTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_GetModelTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).GetModelTree(ctx, req.(*GetModelTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Models_GetModelBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsServer).GetModelBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Models_GetModelBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsServer).GetModelBlob(ctx, req.(*GetModelBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Models_ServiceDesc is the grpc.ServiceDesc for Models service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Models_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matrixhub.v1alpha1.Models",
	HandlerType: (*ModelsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModelTaskLabels",
			Handler:    _Models_ListModelTaskLabels_Handler,
		},
		{
			MethodName: "ListModelFrameLabels",
			Handler:    _Models_ListModelFrameLabels_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Models_ListModels_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _Models_GetModel_Handler,
		},
		{
			MethodName: "CreateModel",
			Handler:    _Models_CreateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _Models_DeleteModel_Handler,
		},
		{
			MethodName: "ListModelRevisions",
			Handler:    _Models_ListModelRevisions_Handler,
		},
		{
			MethodName: "ListModelCommits",
			Handler:    _Models_ListModelCommits_Handler,
		},
		{
			MethodName: "GetModelCommit",
			Handler:    _Models_GetModelCommit_Handler,
		},
		{
			MethodName: "GetModelTree",
			Handler:    _Models_GetModelTree_Handler,
		},
		{
			MethodName: "GetModelBlob",
			Handler:    _Models_GetModelBlob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha1/model.proto",
}
